spring:
  # \u767B\u9646\u6240\u9700\u7684\u8D26\u53F7\u5BC6\u7801
  security:
    user:
      name: evan
      password: 123
  boot:
    admin:
      client:
        # \u4FBF\u4E8E\u5BA2\u6237\u7AEF\u53EF\u4EE5\u5728\u53D7\u4FDD\u62A4\u7684\u670D\u52A1\u5668\u4E0A\u6CE8\u518Capi
        username: evan
        password: 123
        # \u4FBF\u670D\u52A1\u5668\u53EF\u4EE5\u8BBF\u95EE\u53D7\u4FDD\u62A4\u7684\u5BA2\u6237\u7AEF\u7AEF\u70B9
        instance:
          metadata:
            user:
              name: evan
              password: 123






